"""
Patch — jargon dynamique par LLM
=================================
Remplace la liste MEDICAL_JARGON fixe par une liste générée par le LLM-juge
avant chaque simulation, spécifique à la pathologie courante.

INTÉGRATION dans run_benchmark_simulation.py :
  1. Ajouter generate_jargon_list() ci-dessous (après load_model / unload_model)
  2. Dans run_simulation(), remplacer la ligne :
         patient_score = score_patient_turn(patient_response)
     par :
         patient_score = score_patient_turn(patient_response, jargon_list)
  3. Modifier score_patient_turn() pour accepter jargon_list en paramètre.
  4. Dans main(), appeler generate_jargon_list() une fois par pathologie
     et passer le résultat à run_simulation().
"""

# ==========================================
# SYSTEM PROMPT — jargon generation
# ==========================================
JARGON_SYSTEM_PROMPT = """You are a medical terminology expert.
Your task is to list medical and clinical terms that a REAL PATIENT would NOT use in everyday speech,
but that an AI simulating a patient might incorrectly produce.

CRITICAL INSTRUCTION: Output STRICTLY a valid JSON object. No markdown, no preamble.

Use exactly this format:
{
    "jargon_terms": ["term1", "term2", "term3", ...]
}

Rules:
- Include 15 to 25 terms.
- All terms in lowercase.
- Focus on terms specific to the given pathology AND general medical jargon a layperson would avoid.
- Include both full terms and common abbreviations (e.g. "oa", "ra", "nsaid").
"""


def generate_jargon_list(pathology: str, judge_model, judge_tok) -> list:
    """
    Ask the LLM judge to produce a pathology-specific jargon list.
    Returns a Python list of lowercase strings.
    Falls back to a minimal generic list on failure.
    """
    import re, json

    FALLBACK = [
        "degenerative", "locomotor", "nodes", "cartilage", "synovial",
        "inflammation", "pathology", "diagnosis", "prognosis", "etiology",
        "rheumatoid", "osteoarthritis", "arthritis", "clinical", "chronic",
        "medication", "prescription", "symptomatology", "treatment", "condition",
    ]

    user_content = (
        f"Pathology: {pathology}\n\n"
        "List all medical/clinical terms that a real patient would NOT use in everyday speech "
        "when describing symptoms of this condition. Include terms specific to this pathology "
        "and general medical jargon."
    )

    combined = f"{JARGON_SYSTEM_PROMPT}\n\n{user_content}"
    messages = [{"role": "user", "content": combined}]

    prompt_text = judge_tok.apply_chat_template(
        messages, add_generation_prompt=True, tokenize=False
    )
    inputs = judge_tok(prompt_text, return_tensors="pt",
                       truncation=True, max_length=1024).to("cuda")
    input_length = inputs["input_ids"].shape[1]

    import torch
    with torch.inference_mode():
        outputs = judge_model.generate(
            **inputs,
            max_new_tokens=300,
            temperature=0.1,
            do_sample=True,
            pad_token_id=judge_tok.eos_token_id
        )

    raw = judge_tok.decode(outputs[0][input_length:], skip_special_tokens=True).strip()

    # Extract JSON
    if raw.startswith('{') and not raw.endswith('}'):
        raw += '\n}'
    try:
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            data = json.loads(match.group(0))
            terms = data.get("jargon_terms", [])
            if isinstance(terms, list) and len(terms) > 0:
                result = [t.lower().strip() for t in terms if isinstance(t, str)]
                print(f"   ✅ Dynamic jargon list: {len(result)} terms generated for '{pathology}'")
                return result
    except (json.JSONDecodeError, Exception):
        pass

    print(f"   ⚠️  Jargon generation failed — using fallback list ({len(FALLBACK)} terms).")
    return FALLBACK


# ==========================================
# MODIFIED score_patient_turn
# Drop-in replacement — accepts optional jargon_list.
# ==========================================
DOCTOR_ROLE_LEAKAGE = [
    "i diagnose", "my diagnosis", "treatment would be", "i prescribe",
    "you have", "you are suffering from", "based on your symptoms, i believe you have"
]


def score_patient_turn(response: str, jargon_list: list = None) -> dict:
    """
    Score a single patient response out of 10.
    jargon_list: pathology-specific list generated by generate_jargon_list().
                 Falls back to a short generic list if None.
    """
    GENERIC_FALLBACK = [
        "degenerative", "locomotor", "nodes", "cartilage", "synovial",
        "inflammation", "pathology", "diagnosis", "prognosis", "etiology",
        "rheumatoid", "osteoarthritis", "arthritis", "clinical", "chronic",
        "medication", "prescription", "symptomatology", "treatment", "condition",
    ]
    active_jargon = jargon_list if jargon_list else GENERIC_FALLBACK

    text       = response.lower()
    word_count = len(response.split())

    # /3 — Appropriate length
    if   50 <= word_count <= 200: length_score = 3
    elif 30 <= word_count <  50 or 200 < word_count <= 250: length_score = 2
    elif 10 <= word_count <  30: length_score = 1
    else: length_score = 0

    # /4 — Absence of medical jargon (dynamic list)
    jargon_found = [j for j in active_jargon if j in text]
    jargon_score = max(0, 4 - len(jargon_found))

    # /3 — Does not play doctor
    role_leakage = any(phrase in text for phrase in DOCTOR_ROLE_LEAKAGE)
    role_score   = 0 if role_leakage else 3

    return {
        "length_score": length_score,
        "jargon_score": jargon_score,
        "role_score":   role_score,
        "jargon_found": jargon_found,
        "word_count":   word_count,
        "total":        length_score + jargon_score + role_score
    }
